#include <iostream>
#include <stdexcept>
#include <cassert>
#include <string>

using namespace std;
/*
int divide(int num, int denom)
{
   //assert(denom != 0); //next piece of code will not be executed
   if(denom == 0) { throw 0;}
   else if (num == 0) {
       throw string("Num is 0...Bad!");
   }
   return(num/denom);
}

int f1(int x)
{
    int res = -1;
	try
    {
	    res = divide(x, x-2);
    }
    catch(int a)
    {
    	cout <<"Error!!" << endl;
    }
    catch(string& error)
    {
    	cout << error << endl;
    }
    catch(...)
    {
    	cout << "Unknown Execption" << endl;
    }
    return res;
}

int main()
{
   int res = -1, a;
   cout << "Enter: " << endl;
   cin >> a;
   res = f1(a);
   cout << res << endl;
   return 0;
}*/
